# Generated by Django 4.1.5 on 2023-01-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensionteam',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
