# Generated by Django 4.1.5 on 2023-01-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_dimensionhappiness_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DimensionHappiness',
            new_name='DimensionHappinessLevel',
        ),
    ]
