# Generated by Django 4.1.5 on 2023-01-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
