# Generated by Django 4.1.5 on 2023-01-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_checkin_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='responses',
            field=models.JSONField(default=list),
        ),
    ]
