# Generated by Django 4.1.5 on 2023-01-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_alter_checkin_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='score',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='responses',
            field=models.IntegerField(default=0),
        ),
    ]
