# Generated by Django 4.1.5 on 2023-01-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('daily', '0004_remove_checkin_score_alter_checkin_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='team',
        ),
        migrations.AddField(
            model_name='checkin',
            name='team',
            field=models.ManyToManyField(to='team.team'),
        ),
    ]
