# Generated by Django 4.1.5 on 2023-01-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0005_remove_checkin_team_checkin_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='team',
            new_name='teams',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='responses',
            field=models.JSONField(default=list),
        ),
    ]
