# Generated by Django 4.1.5 on 2023-01-22 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daily', '0006_rename_team_checkin_teams_alter_checkin_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='teams',
        ),
        migrations.AddField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
